.\" qjar.1 - man page for the Qore JAR generation helper
.\"
.\" Copyright (C) 2026 Qore Technologies, s.r.o.
.\"
.TH QJAR 1 "2026 July 10" "Qore 3.0" "Qore Programming Language"
.SH NAME
qjar \- generate Java class files and a JAR from Qore modules or reflection trees
.SH SYNOPSIS
.B qjar
[\fIoptions\fP]
\fB\-i=\fP\fIinput_root_dir\fP
[\fB\-m=\fP\fImodule\fP]
[\fB\-o=\fP\fIoutput_jar\fP]
.SH DESCRIPTION
\fBqjar\fR uses the Qore \fBjni\fR module to emit JVM class files corresponding
to a Qore module's public API, then packages them into a JAR.
It is part of the Qore documentation build pipeline and is also useful when
embedding Qore code in a Java host environment.
.PP
If \fB\-c\fP / \fB\-\-classes\fP is given, \fBqjar\fR walks the input directory
and generates JVM class files from Java source files found there.
.PP
If the \fBjni\fR module is not available a warning is printed and no class
files are produced; the build continues.
.SH OPTIONS
.TP
.BR \-c ", " \-\-classes
Scan the input directory for Java source files and generate their class files.
.TP
.BR \-d ", " \-\-dry\-run
Do not create any output; only print paths that would be written.
.TP
.BR \-i ", " \-\-input =\fIdir\fP
Root staging directory for generated classes and JAR input (required).
.TP
.BR \-m ", " \-\-module =\fImodule\fP
Qore module to generate class files for.
.TP
.BR \-o ", " \-\-output =\fIjar\fP
Path of the JAR file to create.
.TP
.BR \-v ", " \-\-verbose [=\fIlevel\fP]
Show additional output.
.TP
.BR \-h ", " \-\-help
Show help text.
.SH SEE ALSO
.BR qdx (1),
.BR qore (1),
.BR jar (1)
.SH AUTHORS
Qore Technologies, s.r.o.
.SH COPYRIGHT
Copyright \(co 2026 Qore Technologies, s.r.o.
.br
Licensed under MIT.
