/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file cppapiuser-module.h internal declarations for the cppapiuser test module

    Qore Programming Language

    Copyright (C) 2003 - 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_CPPAPIUSER_MODULE_H
#define _QORE_CPPAPIUSER_MODULE_H

#include "QoreCppApiTestApi.h"

#include <atomic>

//! returns the resolved producer API, resolving and caching it on the first call
/** @param xsink Qore-language exceptions are raised here

    @return the producer's API struct, or nullptr if an exception was raised
*/
DLLLOCAL const QoreCppApiTestApi* cppapiuser_get_api(ExceptionSink* xsink);

//! releases an opaque producer handle when it goes out of scope
/** An opaque handle from another module has no destructor the consumer can see, so the only
    exception-safe way to hold one is a scope guard over the API struct's \c deref member.
*/
class CounterHolder {
public:
    DLLLOCAL CounterHolder(const QoreCppApiTestApi* api, QoreCppApiTestCounter* c) : api(api), c(c) {
    }

    DLLLOCAL ~CounterHolder() {
        if (c) {
            api->counter_deref(c);
        }
    }

    DLLLOCAL QoreCppApiTestCounter* operator*() const {
        return c;
    }

    CounterHolder(const CounterHolder&) = delete;
    CounterHolder& operator=(const CounterHolder&) = delete;

private:
    const QoreCppApiTestApi* api;
    QoreCppApiTestCounter* c;
};

// generated by qpp from ql_cppapiuser.qpp
DLLLOCAL void init_cppapiuser_functions(QoreNamespace& ns);

#include "QC_ProgramContextProbe.h"

#endif // _QORE_CPPAPIUSER_MODULE_H
