/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file avrocppapi-module.h internal declarations for the avrocppapi test module

    Qore Programming Language

    Copyright (C) 2003 - 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_AVROCPPAPI_MODULE_H
#define _QORE_AVROCPPAPI_MODULE_H

#include <qore/Qore.h>
#include <qore/QoreAvroApi.h>

//! returns the resolved avro C++ API, resolving and caching it on the first call
/** @param xsink Qore-language exceptions are raised here

    @return the avro module's API struct, or nullptr if an exception was raised
*/
DLLLOCAL const QoreAvroApi* avrocppapi_get_api(ExceptionSink* xsink);

//! parses a schema from JSON text through the C++ API; the caller owns the handle returned
DLLLOCAL QoreAvroSchemaRef* avrocppapi_parse(const QoreAvroApi* api, const QoreString& schema_json,
        ExceptionSink* xsink);

// generated by qpp from ql_avrocppapi.qpp
DLLLOCAL void init_avrocppapi_functions(QoreNamespace& ns);

#endif // _QORE_AVROCPPAPI_MODULE_H
