/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file protobuf-module.h protobuf module header file */
/*
    Qore protobuf module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_PROTOBUF_MODULE_H
#define _QORE_PROTOBUF_MODULE_H

#include <qore/Qore.h>
#include <qore/QoreSandboxManager.h>
#include <qore/qore_thread.h>

#include <google/protobuf/stubs/common.h>

// Detect protobuf API version
// Protobuf v22+ (GOOGLE_PROTOBUF_VERSION >= 4022000):
//   - AddError/AddWarning -> RecordError/RecordWarning
//   - always_print_primitive_fields -> always_print_fields_with_no_presence
//   - SourceTree::Open takes absl::string_view
//   - full_name() returns absl::string_view instead of const std::string&
#if GOOGLE_PROTOBUF_VERSION >= 4022000
#define QORE_PROTOBUF_V22_PLUS 1
#include <absl/strings/string_view.h>
#endif

// Forward declarations
class QoreProtobufSchema;

// Hashdecl init functions (generated by QPP from QC_ProtobufSchema.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_ProtobufServiceInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_ProtobufMethodInfo(QoreNamespace& ns);

// Global hashdecl pointers (initialized in protobuf-module.cpp)
extern const TypedHashDecl* hashdeclProtobufServiceInfo;
extern const TypedHashDecl* hashdeclProtobufMethodInfo;

// Namespace
extern QoreNamespace ProtobufNs;

#endif // _QORE_PROTOBUF_MODULE_H
