/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file avro-module.cpp avro module implementation */
/*
    Qore avro module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#include "avro-module.h"
#include "QC_AvroSchema.h"
#include "QC_AvroFileReader.h"
#include "QC_AvroFileWriter.h"

#include <atomic>

// generated by qpp from ql_avro.qpp
DLLLOCAL void init_avro_constants(QoreNamespace& ns);

static void avro_module_init(QoreModuleInitContext& ctx, ExceptionSink& xsink);
static void avro_module_ns_init(QoreNamespace* rns, QoreNamespace* qns, ExceptionSink& xsink);
static void avro_module_delete();

extern "C" DLLEXPORT void avro_qore_module_desc(QoreModuleInfo& mod_info) {
    mod_info.name = "avro";
    mod_info.version = PACKAGE_VERSION;
    mod_info.desc = "Qore avro module implementing Apache Avro schema parsing, the binary datum "
                    "codec and object container files";
    mod_info.author = "Qore Technologies, s.r.o.";
    mod_info.url = "https://qore.org";
    mod_info.api_major = QORE_MODULE_API_MAJOR;
    mod_info.api_minor = QORE_MODULE_API_MINOR;
    mod_info.init = avro_module_init;
    mod_info.ns_init = avro_module_ns_init;
    mod_info.del = avro_module_delete;
    mod_info.license = QL_MIT;
    mod_info.license_str = "MIT";
}

// the namespace name must be the full path from the root namespace; see
// design/qore-module-structure.md
QoreNamespace AvroNs("Qore::Avro");

const TypedHashDecl* hashdeclAvroFieldInfo = nullptr;

// the json module's C++ API, resolved on first use; binary modules are only unloaded at shutdown,
// so the pointer is valid for the life of the process.  Resolution is deliberately lazy rather
// than done in avro_module_init(): a Program that only encodes and decodes against schemas it
// already holds never needs the json module, and nothing should load a module it will not use.
static std::atomic<const QoreJsonApi*> json_api{nullptr};

const QoreJsonApi* avro_get_json_api(ExceptionSink* xsink) {
    const QoreJsonApi* api = json_api.load(std::memory_order_acquire);
    if (!api) {
        api = qore_json_api(xsink);
        if (!api) {
            assert(*xsink);
            return nullptr;
        }
        json_api.store(api, std::memory_order_release);
    }
    return api;
}

static void avro_module_init(QoreModuleInitContext& ctx, ExceptionSink& xsink) {
    // AvroFieldInfo has an AvroSchema member, so the class must be registered first
    AvroNs.addSystemClass(initAvroSchemaClass(AvroNs));
    hashdeclAvroFieldInfo = init_hashdecl_AvroFieldInfo(AvroNs);
    AvroNs.addSystemClass(initAvroFileReaderClass(AvroNs));
    AvroNs.addSystemClass(initAvroFileWriterClass(AvroNs));
    init_avro_constants(AvroNs);
}

static void avro_module_ns_init(QoreNamespace* rns, QoreNamespace* qns, ExceptionSink& xsink) {
    qns->addNamespace(AvroNs.copy());
}

static void avro_module_delete() {
}
