# Copyright (c) 2026 Qore Technologies, s.r.o.
#
# Writes the header that gives libqore its AOT runtime identity.
#
# The identity is the SHA-256 digest of the source part of the qcc format
# fingerprint (qcc-format.stamp): the path, size and content hash of every
# libqore source that can change the native code qcc emits or how the runtime
# reads an emitted artifact back (_qcc_format_sources in CMakeLists.txt).
# Every AOT module records the identity of the libqore that compiled it, and
# the module loader refuses an AOT module whose identity differs from its own;
# see "AOT Module Runtime Identity" in
# design/aot-object-files-and-module-artifacts.md.
#
# The "@build-config" entry of the fingerprint (build type, compiler and
# compiler flags) is left out: those settings decide whether in-tree qmods are
# rebuilt, but they do not change the contract between generated code and the
# runtime, so a debug libqore can load modules compiled by a release libqore
# built from the same sources.
#
# The header is only rewritten when the identity changes, so the one
# translation unit that includes it is only recompiled then.
#
# Inputs:
#   INPUT  - the qcc format fingerprint written by QoreWriteContentDigest.cmake
#   OUTPUT - the header to write

cmake_policy(SET CMP0007 NEW)

if (NOT DEFINED INPUT OR "${INPUT}" STREQUAL "")
    message(FATAL_ERROR "INPUT is required")
endif ()
if (NOT DEFINED OUTPUT OR "${OUTPUT}" STREQUAL "")
    message(FATAL_ERROR "OUTPUT is required")
endif ()
if (NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "qcc format fingerprint '${INPUT}' does not exist")
endif ()

file(STRINGS "${INPUT}" _lines ENCODING UTF-8)
set(_identity_input "qore-aot-runtime-identity-v1\n")
set(_source_entries 0)
foreach (_line IN LISTS _lines)
    if (_line MATCHES "^@build-config\t")
        continue()
    endif ()
    if (_line MATCHES "\t")
        math(EXPR _source_entries "${_source_entries} + 1")
    endif ()
    string(APPEND _identity_input "${_line}\n")
endforeach ()
if (NOT _source_entries)
    message(FATAL_ERROR "qcc format fingerprint '${INPUT}' has no source entries")
endif ()

string(SHA256 _identity "${_identity_input}")

set(_content "/* generated by cmake/QoreWriteAOTRuntimeIdentity.cmake from ${INPUT}; do not edit */
#ifndef _QORE_INTERN_QORE_AOT_RUNTIME_IDENTITY_H
#define _QORE_INTERN_QORE_AOT_RUNTIME_IDENTITY_H
#define QORE_AOT_RUNTIME_IDENTITY \"${_identity}\"
#endif
")

get_filename_component(_output_dir "${OUTPUT}" DIRECTORY)
if (_output_dir)
    file(MAKE_DIRECTORY "${_output_dir}")
endif ()
set(_current)
if (EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _current)
endif ()
if (NOT "${_current}" STREQUAL "${_content}")
    file(WRITE "${OUTPUT}" "${_content}")
endif ()
