# Copyright (C) 2026 Qore Technologies, s.r.o.
# SPDX-License-Identifier: MIT

# Installed AOT consumers must not inherit the package builder's compiler
# wrappers, package notes, or environment-dependent linker settings.
set(QORE_AOT_LINK_FLAGS "" CACHE STRING "Additional linker flags for AOT consumers (independent of Qore build flags)")

function(_qore_collect_link_arguments output ancestors)
    set(flags "")
    foreach(library IN LISTS ARGN)
        if(library MATCHES "^\\$<LINK_ONLY:(.*)>$")
            set(library "${CMAKE_MATCH_1}")
        endif()
        if(library STREQUAL "")
            continue()
        elseif(TARGET "${library}")
            if(library IN_LIST ancestors)
                message(FATAL_ERROR "Cyclic AOT link dependency: ${ancestors};${library}")
            endif()
            get_target_property(type "${library}" TYPE)
            if(NOT type STREQUAL "INTERFACE_LIBRARY")
                # Resolve real and imported libraries at generation time; this
                # also respects configuration-specific imported locations.
                list(APPEND flags "$<TARGET_FILE:${library}>")
            endif()
            get_target_property(directories "${library}" INTERFACE_LINK_DIRECTORIES)
            if(directories)
                foreach(directory IN LISTS directories)
                    list(APPEND flags "-L${directory}")
                endforeach()
            endif()
            get_target_property(options "${library}" INTERFACE_LINK_OPTIONS)
            if(options)
                foreach(option IN LISTS options)
                    string(REGEX REPLACE "^LINKER:" "-Wl," option "${option}")
                    list(APPEND flags "${option}")
                endforeach()
            endif()
            get_target_property(dependencies "${library}" INTERFACE_LINK_LIBRARIES)
            if(dependencies)
                _qore_collect_link_arguments(transitive "${ancestors};${library}" ${dependencies})
                list(APPEND flags ${transitive})
            endif()
        elseif(library MATCHES "::" OR library MATCHES "\\$<")
            message(FATAL_ERROR "Unresolved AOT link dependency: ${library}")
        else()
            if(NOT library MATCHES "^-" AND NOT IS_ABSOLUTE "${library}")
                set(library "-l${library}")
            endif()
            list(APPEND flags "${library}")
        endif()
    endforeach()
    set(${output} "${flags}" PARENT_SCOPE)
endfunction()

function(qore_aot_link_arguments output)
    _qore_collect_link_arguments(flags "" ${ARGN})
    set(${output} "${flags}" PARENT_SCOPE)
endfunction()

function(qore_generate_aot_link_config output base dynamic static)
    set(inputs "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/qore-aot-link/$<CONFIG>")
    set(dependencies "${inputs}/base" "${inputs}/extra")
    file(GENERATE OUTPUT "${inputs}/base" CONTENT "${base}")
    file(GENERATE OUTPUT "${inputs}/extra" CONTENT "${QORE_AOT_LINK_FLAGS}")
    foreach(kind dynamic static)
        set(index 0)
        foreach(argument IN LISTS ${kind})
            # One argument per file avoids lossy shell/list quoting before
            # TARGET_FILE and configuration expressions have been evaluated.
            file(GENERATE OUTPUT "${inputs}/${kind}-${index}" CONTENT "${argument}")
            list(APPEND dependencies "${inputs}/${kind}-${index}")
            math(EXPR index "${index} + 1")
        endforeach()
        file(GENERATE OUTPUT "${inputs}/${kind}-count" CONTENT "${index}")
        list(APPEND dependencies "${inputs}/${kind}-count")
    endforeach()
    set(writer "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/QoreWriteAOTLinkConfig.cmake")
    add_custom_command(OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" "-DINPUT=${inputs}" "-DOUTPUT=${output}" -P "${writer}"
        DEPENDS ${dependencies} "${writer}"
        COMMENT "Generating portable AOT linker configuration" VERBATIM)
    add_custom_target(qore-aot-link-config DEPENDS "${output}")
endfunction()
