# Copyright (C) 2026 Qore Technologies, s.r.o.
# SPDX-License-Identifier: MIT
# Run after generation so target locations can be quoted as complete arguments.
file(READ "${INPUT}/base" content)
file(READ "${INPUT}/extra" extra)
if(extra MATCHES "[\r\n]")
    message(FATAL_ERROR "AOT linker flags must occupy one configuration line")
endif()
foreach(kind dynamic static)
    file(READ "${INPUT}/${kind}-count" count)
    if(NOT count MATCHES "^[0-9]+$")
        message(FATAL_ERROR "Invalid AOT linker argument count")
    endif()
    set(flags "")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            file(READ "${INPUT}/${kind}-${index}" argument)
            if(argument MATCHES "[\r\n]")
                message(FATAL_ERROR "AOT linker arguments cannot contain line breaks")
            endif()
            if(argument STREQUAL "")
                continue()
            elseif(argument MATCHES "^SHELL:(.*)$")
                string(APPEND flags " ${CMAKE_MATCH_1}")
            elseif(WIN32)
                string(REPLACE "\"" "\\\"" argument "${argument}")
                string(APPEND flags " \"${argument}\"")
            else()
                string(REPLACE "'" "'\\''" argument "${argument}")
                string(APPEND flags " '${argument}'")
            endif()
        endforeach()
    endif()
    string(STRIP "${flags} ${extra}" flags)
    string(APPEND content "${kind}_libs=${flags}\n")
endforeach()
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(content STREQUAL previous)
        return()
    endif()
endif()
# Leave the previous valid configuration intact if collecting inputs fails.
file(WRITE "${OUTPUT}.tmp" "${content}")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
