#ifndef _QORE_VERSION_H
#define _QORE_VERSION_H
#define QORE_VERSION_MAJOR @VERSION_MAJOR@
#define QORE_VERSION_MINOR @VERSION_MINOR@
#define QORE_VERSION_SUB @VERSION_SUB@
#define QORE_VERSION_PATCH @VERSION_PATCH@
#define QORE_VERSION "@VERSION@"
#define QORE_VERSION_CODE @VERSION_MAJOR@@VERSION_FORMATTED_MINOR@@VERSION_FORMATTED_SUB@
#define QORE_HAVE_GENERIC_CLASSES 1
#define QORE_HAVE_COLUMNAR_RESULT_V2 1
#define QORE_HAVE_EXTERNAL_BUFFER_STORAGE 1
#define QORE_HAVE_ARROW_DATAFRAME_INTEROP 1
#endif
